List-manager/src/List-manager/Models/AccountViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace List_manager.Models.AccountViewModels
{
    public class LoginViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }
}

List-manager/src/List-manager/Controllers/MALAccountController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using List_manager.Models;
using System.Security.Claims;
using Microsoft.Extensions.Caching.Memory;

namespace List_manager.Controllers
{
    public class MALAccountController : Controller
    {

        private IMemoryCache _cache;

        public MALAccountController(IMemoryCache cache)
        {
            _cache = cache;
        }

        // GET: /MALAccount/Login
        [HttpGet]
        public IActionResult Login(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        // GET: /MALAccount/Login
        [HttpPost]
        public async Task<IActionResult> Login(MALUserLogin malUser, string returnUrl = null)
        {
            //query the api

            //if the response return is 200 then its aok
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var success = await MALApi.MALVerify(malUser.Username, malUser.Password);

                if (success)
                {
                    var claims = new List<Claim>
                    {
                        new Claim("Username", malUser.Username, ClaimValueTypes.String),
                        new Claim("Secret", malUser.Password, ClaimValueTypes.String)
                    };

                    var userIdentity = new ClaimsIdentity(claims, "MAL");

                    var principal = new ClaimsPrincipal(userIdentity);

                    //TODO: might add in an expiration date
                    await HttpContext.Authentication.SignInAsync("MALCookie", principal);

                    _cache.CreateEntry("MALAnimeList");

                    _cache.Set("MALAnimeList", new MALUserDictionary(await MALApi.MALUserInfo(malUser.Username, "all", "anime")));

                    return Redirect(returnUrl);

                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return View(malUser);
                }
            }

            return View(malUser);
        }

        //
        // POST: /Account/LogOff
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogOff()
        {
            await HttpContext.Authentication.SignOutAsync("MALCookie");
            
            //TODO redirect to index page
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }


    }
}

List-manager/src/List-manager/Views/MALAccount/Login.cshtml
@using System.Collections.Generic
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Http.Authentication
@model MALUserLogin

@{
    ViewData["Title"] = "Log in";
}

<h2>@ViewData["Title"].</h2>
<div class="row">
    <div class="col-md-8">
        <section>
            <form asp-controller="MALAccount" asp-action="Login" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal">
                <h4>Use a MAL Account to log in.</h4>
                <hr />
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Username" class="col-md-2 control-label"></label>
                    <div class="col-md-10">
                        <input asp-for="Username" class="form-control" />
                        <span asp-validation-for="Username" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="col-md-2 control-label"></label>
                    <div class="col-md-10">
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" class="btn btn-default">Log in</button>
                    </div>
                </div>
                
            </form>
        </section>
    </div>
   
</div>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}