List-manager/src/List-manager/Models/Anime.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace List_manager.Models
{
    public class Anime : MALObjects.Entry
    {

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

      

    }

}

List-manager/src/List-manager/Controllers/AnimesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using List_manager.Data;
using List_manager.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Identity;

namespace List_manager.Controllers
{
    [Authorize(Policy = "DefaultPolicy")]
    public class AnimesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AnimesController(ApplicationDbContext context)
        {
            _context = context;
        }

        

        // GET: Animes
        public async Task<IActionResult> Index()
        { 

            return View(await _context.Anime.ToListAsync());
           
        }

        // GET: Animes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anime = await _context.Anime.SingleOrDefaultAsync(m => m.ID == id);
            if (anime == null)
            {
                return NotFound();
            }

            return View(anime);
        }

        // GET: Animes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Animes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MALID,End_Date,English,Episodes,Image,Score,Start_Date,Status,Synonyms,Synopsis,Title,Type")] Anime anime)
        {
            if (ModelState.IsValid)
            {
                _context.Add(anime);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(anime);
        }

        // GET: Animes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anime = await _context.Anime.SingleOrDefaultAsync(m => m.ID == id);
            if (anime == null)
            {
                return NotFound();
            }
            return View(anime);
        }

        // POST: Animes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MALID,End_Date,English,Episodes,Image,Score,Start_Date,Status,Synonyms,Synopsis,Title,Type")] Anime anime)
        {
            if (id != anime.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(anime);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnimeExists(anime.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(anime);
        }

        // GET: Animes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anime = await _context.Anime.SingleOrDefaultAsync(m => m.ID == id);
            if (anime == null)
            {
                return NotFound();
            }

            return View(anime);
        }

        // POST: Animes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var anime = await _context.Anime.SingleOrDefaultAsync(m => m.ID == id);
            _context.Anime.Remove(anime);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool AnimeExists(int id)
        {
            return _context.Anime.Any(e => e.MALID == id);
        }

        /*
        public async Task<IActionResult> Add(int id)
        {
            try
            {
                TempData["returnUrl"] = Request.Headers["Referer"].ToString();


                Anime anime = ((AnimeList)_cache.Get("SearchResults")).EntryList[id];


                int f_id = 0;
                if (!AnimeExists(anime.MALID))
                {
                    _context.Add(anime);
                    await _context.SaveChangesAsync();

                    f_id = anime.ID;
                }
                else
                {
                    f_id = _context.Anime.First(f => f.MALID == anime.MALID).ID;
                }


                //Add to the relational table for the user and the anime added

                return RedirectToAction("Add", "UserAnime", new { animeId = f_id });

            }
            catch (Exception ex)//Accessing the _cache will fail
            {
                //log error
                //inform the user and redirect
            }

            return RedirectToAction("Search");
        }
        */

        [HttpPost, ActionName("Add")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToDB([Bind("MALID,End_Date,English,Episodes,Image,Score,Start_Date,Status,Synonyms,Synopsis,Title,Type")]Anime anime)
        {
            TempData["returnUrl"] = Request.Headers["Referer"].ToString();
            if (ModelState.IsValid)
            {
                int f_id = 0;
                if (!AnimeExists(anime.MALID))
                {
                    _context.Add(anime);
                    await _context.SaveChangesAsync();

                    f_id = anime.ID;
                }
                else
                {
                    f_id = _context.Anime.First(f => f.MALID == anime.MALID).ID;
                }


                //Add to the relational table for the user and the anime added

                return RedirectToAction("Add", "UserAnime", new { animeId = f_id });
            }
            return Redirect(Request.Headers["Referer"].ToString());
        }
    }
}

List-manager/src/List-manager/Views/Animes/Create.cshtml
@model List_manager.Models.Anime

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Anime</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        
        <div class="form-group">
            <label asp-for="End_Date" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="End_Date" class="form-control" />
                <span asp-validation-for="End_Date" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="English" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="English" class="form-control" />
                <span asp-validation-for="English" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Episodes" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Episodes" class="form-control" />
                <span asp-validation-for="Episodes" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Image" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Score" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Score" class="form-control" />
                <span asp-validation-for="Score" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Start_Date" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Start_Date" class="form-control" />
                <span asp-validation-for="Start_Date" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Status" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Synonyms" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Synonyms" class="form-control" />
                <span asp-validation-for="Synonyms" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Synopsis" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Synopsis" class="form-control" />
                <span asp-validation-for="Synopsis" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Title" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Type" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="User_Status" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="User_Status" class="form-control" />
                <span asp-validation-for="User_Status" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

List-manager/src/List-manager/Views/Animes/Delete.cshtml
@model List_manager.Models.Anime

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Anime</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MALID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MALID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.End_Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.End_Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.English)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.English)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Episodes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Episodes)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Start_Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Start_Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Synonyms)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Synonyms)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Synopsis)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Synopsis)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User_Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User_Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

List-manager/src/List-manager/Views/Animes/Details.cshtml
@model List_manager.Models.Anime

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Anime</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MALID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MALID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.End_Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.End_Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.English)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.English)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Episodes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Episodes)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Start_Date)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Start_Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Synonyms)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Synonyms)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Synopsis)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Synopsis)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        @*<dt>
        @Html.DisplayNameFor(model => model.User_Status)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.User_Status)
    </dd>*@
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

List-manager/src/List-manager/Views/Animes/Edit.cshtml
@model List_manager.Models.Anime

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Anime</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ID" />
       
        <div class="form-group">
            <label asp-for="End_Date" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="End_Date" class="form-control" />
                <span asp-validation-for="End_Date" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="English" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="English" class="form-control" />
                <span asp-validation-for="English" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Episodes" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Episodes" class="form-control" />
                <span asp-validation-for="Episodes" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Image" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Score" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Score" class="form-control" />
                <span asp-validation-for="Score" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Start_Date" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Start_Date" class="form-control" />
                <span asp-validation-for="Start_Date" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Status" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Synonyms" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Synonyms" class="form-control" />
                <span asp-validation-for="Synonyms" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Synopsis" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Synopsis" class="form-control" />
                <span asp-validation-for="Synopsis" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Title" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Type" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="User_Status" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="User_Status" class="form-control" />
                <span asp-validation-for="User_Status" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

List-manager/src/List-manager/Views/Animes/Index.cshtml
@model IEnumerable<List_manager.Models.UserAnime>

@{
    ViewData["Title"] = "Index";
}

<h2>Anime List</h2>

<p>
    <a asp-action="Search" asp-controller="Animes">Add to list</a>
</p>

    <div class="container-fluid bg-2">

        @if (Model.Count<UserAnime>() != 0)
        {
            <table class="table table-bordered table-striped text-center table-responsive">
                <tr>

                    <th>
                        Title
                    </th>
                   
                    <th>
                        Score
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        User Status
                    </th>
                </tr>

                <tbody>

                    @foreach (var item in Model)
                    {


                        <tr>
                            <td class="title-desc col-md-7">

                                <div class="col-sm-2">
                                    <input type="hidden" asp-for="@item.Anime.Image" />
                                    <img src="@Url.Content(@item.Anime.Image)" class="img-responsive">
                                </div>

                                <div class="col-sm-10">
                                    <a href="@Url.Content(@item.Anime.GetLink())">@Html.DisplayFor(modelItem => item.Anime.Title)</a>

                                    @if (!String.IsNullOrEmpty(@item.Anime.English))
                                    {

                                        <p>Eng: @Html.DisplayFor(modelItem => item.Anime.English)</p>
                                    }

                                    @if (!String.IsNullOrEmpty(@item.Anime.Synonyms))
                                    {
                                        <p>Syn: @Html.DisplayFor(modelItem => item.Anime.Synonyms)</p>
                                    }

                                    <p>Type: @Html.DisplayFor(modelItem => item.Anime.Type) (@Html.DisplayFor(modelItem => item.Anime.Episodes) eps)</p>
                                    <p>@item.Anime.GetStartDateNiceFormat() - @item.Anime.GetEndDateNiceFormat()</p>


                                    <button type="button" class="btn btn-info syn-btn" data-toggle="collapse" data-target="#@item.Anime.ID">Synopsis</button>
                                    <div id="@item.Anime.ID" class="collapse">
                                        <p>@Html.Raw(@item.Anime.Synopsis)</p>
                                    </div>


                                </div>
                            </td>


                            <td class="v-center">
                                @Html.DisplayFor(modelItem => item.Anime.Score)
                            </td>

                            <td class="v-center">
                                @Html.DisplayFor(modelItem => item.Anime.Status)@*needs to have a conditional on what to display*@
                            </td>

                            <td class="v-center">
                                @Html.DisplayFor(modelItem => item.User_Status)
                            </td>

                            <td class="v-center">
                                <a asp-action="Edit" asp-route-id="@item.Anime.ID">Edit</a> |
                                <a asp-action="Details" asp-route-id="@item.Anime.ID">Details</a> |
                                <a asp-action="Delete" asp-route-id="@item.Anime.ID">Delete</a>
                            </td>
                        </tr>

                    }
                </tbody>
            </table>
      }
        </div>