List-manager/src/List-manager/Controllers/MALController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using List_manager.Data;
using Microsoft.AspNetCore.Identity;
using List_manager.Models;
using Microsoft.AspNetCore.Authorization;
using System.Net.Http;
using System.Text;
using System.Net.Http.Headers;
using System.Xml.Serialization;
using System.Xml;
using System.IO;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using List_manager.Models.MALObjects;


/*TODO - Once Implemented on the Front End properly finish off*/
namespace List_manager.Controllers
{
    [Authorize(Policy = "MALApiPolicy")]
    public class MALController : Controller
    {

        private readonly ApplicationDbContext _context;
        private IMemoryCache _cache;
        private readonly UserManager<ApplicationUser> _userManager;


        public MALController(ApplicationDbContext context, IMemoryCache cache, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _cache = cache;
            _userManager = userManager;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        //Add

        // GET: MAL/Add
        public IActionResult Add(int malid, string animeName)
        {
            ViewData["anime"] = animeName;
            ViewData["animeID"] = malid;
            return View(new UserAnimeData());
        }

        // POST: MAL/Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("Episode,Status,Score,Storage_Type,Storage_Value,Times_Rewatched," +
            "Rewatch_Value,Date_Start,Date_Finish,Priority,Enable_Discussion,Enable_Rewatching,Comments,Tags")] UserAnimeData data, int animeId)
        {
            MALUserLogin malUser = GetUserCredentials();

            if (malUser == null)
            {
                return RedirectToAction("Login", "MALAccount", new { returnUrl = "/Animes/Search" });
            }

            if (ModelState.IsValid)
            {
                HttpResponseMessage res = await MALApi.MALAdd(malUser.Username, malUser.Password, animeId, data);

                if (res.IsSuccessStatusCode && res.ReasonPhrase == "Created")
                {
                    //Set something to indicate to the user that it was a success
                    
                } else if(!res.IsSuccessStatusCode)
                {
                    //try updating it
                    return await Update(data, animeId);

                } else
                {
                    //something went wrong
                }
               

            }

            return Redirect(Request.Headers["Referer"].ToString());
        }

        //Update
        
        // GET: MAL/Add
        public async Task<IActionResult> Update(int malid, string animeName)
        {
            ViewData["anime"] = animeName;
            ViewData["animeID"] = malid;

            MALUserLogin malUser = GetUserCredentials();

            if (malUser == null)
            {
                return RedirectToAction("Login", "MALAccount", new { returnUrl = "/Animes/Search" });
            }

            var malDict = await GetMALUserDictionary(malUser);

            UserAnimeData userAnimeData = new UserAnimeData(malDict.MALAnimeDictionary[malid]);

            return View(new UserAnimeData());
        }
        

        // POST: MAL/Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update([Bind("Episode,Status,Score,Storage_Type,Storage_Value,Times_Rewatched,Rewatch_Value,Date_Start,Date_Finish,Priority,Enable_Discussion,Enable_Rewatching,Comments,Tags")] UserAnimeData data, int animeId)
        {

            MALUserLogin malUser = GetUserCredentials();

            if(malUser == null)
            {
                return RedirectToAction("Login", "MALAccount", new { returnUrl = "/Animes/Search" });
            }

            if (ModelState.IsValid)
            {
                HttpResponseMessage res = await MALApi.MALUpdate(malUser.Username, malUser.Password, animeId, data);

                if (res.IsSuccessStatusCode)
                {
                    //Set something to indicate to the user that it was a success
                    
                } else
                {
                    string reqMess = await res.Content.ReadAsStringAsync();
                }

            }

            return Redirect(Request.Headers["Referer"].ToString());
        }

        // GET: MAL/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var anime = await _context.Anime.SingleOrDefaultAsync(m => m.ID == id);
            if (anime == null)
            {
                return NotFound();
            }

            return View(anime);
        }

        // POST: MAL/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            MALUserLogin malUser = GetUserCredentials();

            if (malUser == null)
            {
                return RedirectToAction("Login", "MALAccount", new { returnUrl = "/Animes/Search" });
            }

            HttpResponseMessage res = await MALApi.MALDelete(malUser.Username, malUser.Password, id);

            if (res.IsSuccessStatusCode)
            {
                //Set something to indicate to the user that it was a success
                return View();
            }
            else
            {
                string reqMess = await res.Content.ReadAsStringAsync();
            }

            return View();

        }

        // GET: MAL/Search/Bleach
        public async Task<IActionResult> Search(string searchString)
        {

            MALUserLogin malUser = GetUserCredentials();

            if (malUser == null)
            {
                return RedirectToAction("Login", "MALAccount", new { returnUrl = "/Animes/Search" });
            }

            MALSearchList list = new Models.MALObjects.MALSearchList();
            SearchResultViewModel searchResults = new SearchResultViewModel(); 
            if (!String.IsNullOrEmpty(searchString))
            {

                list = await MALApi.MALSearch(malUser.Username, malUser.Password, searchString);
                _cache.CreateEntry("SearchResults");
                _cache.Set("SearchResults", list);

                var user = await GetCurrentUserAsync();
                var userId = user?.Id;

                List<UserAnime> anime = _context.UserAnimes.Where(d => d.ApplicationUserId == userId).Include(u => u.Anime).ToList();

                var malDict = await GetMALUserDictionary(malUser);

                List <Models.MALObjects.MALUserAnime> malList = malDict.MALAnimeDictionary.Values.ToList();

                var combineResults = from entry in list.EntryList
                                     from malAnimeList in malList.Where(f => f.Series_Animedb_Id == entry.MALID).DefaultIfEmpty()
                                     from animeUser in anime.Where(aua => aua.Anime.MALID == entry.MALID).DefaultIfEmpty()
                                     select new EntryResult { Entry = entry, MAL_User_Status = malAnimeList == null ? null : malAnimeList.StatusToString(), User_Status = animeUser == null ? null : animeUser.User_Status};

                searchResults.SearchResults.AddRange(combineResults.ToList());

            }

            return View(searchResults);
        }

        private async Task<MALUserDictionary> GetMALUserDictionary(MALUserLogin malUser)
        {
            
            MALUserDictionary malUserDict;

            if (!_cache.TryGetValue("MALAnimeList", out malUserDict))
            {
                MALUserList malUserList = await MALApi.MALUserInfo(malUser.Username, "all", "anime");

                malUserDict = new MALUserDictionary(malUserList);

                _cache.Set("MALAnimeList", malUserDict);
            }

            return malUserDict;
        }

        private MALUserLogin GetUserCredentials()
        {
            var malCookiesAuth = HttpContext.Authentication.GetAuthenticateInfoAsync("MALCookie");

            if (malCookiesAuth.Result.Description.AuthenticationScheme == null)
            {
                return null;
            }

            //todo add in exception handling if something goes wrong
            var claims = malCookiesAuth.Result.Principal.Claims;
            string userName = claims.First(p => p.Type == "Username").Value;
            string password = claims.First(p => p.Type == "Secret").Value; 

            return new MALUserLogin { Username = userName, Password = password };
        }



    }
}

List-manager/src/List-manager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Anime List Manager</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/style.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="UserAnime" asp-action="Index" class="navbar-brand">Anime List Manager</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="UserAnime" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="MAL" asp-action="Search">MAL Search</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="container text-center">
            <p>&copy; 2017 - List_manager</p>
        </footer>
    </div>

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
    </html>

List-manager/src/List-manager/Views/Shared/_MALEditPartial.cshtml
@model List_manager.Models.UserAnimeData


    <div class="form-horizontal">
        
        <div class="container mal-edit">

            <div class="advanced collapse">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Episode" class="col-md-2 control-label"></label>
                <div class="col-md-10 form-field">
                    <input asp-for="Episode" max="@ViewData["Episodes"]" class="form-control" /> / @ViewData["Episodes"]
                    <span asp-validation-for="Episode" class="text-danger" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="col-md-2 control-label"></label>
                <div class="col-md-10 form-field">
                    <select asp-for="Status" class="form-control">
                        <option value="1">Watching</option>
                        <option value="2">Completed</option>
                        <option value="3">On Hold</option>
                        <option value="4">Dropped</option>
                        <option value="6">Plan to Watch</option>
                    </select>
                    <span asp-validation-for="Status" class="text-danger" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Score" class="col-md-2 control-label"></label>
                <div class="col-md-10 form-field">
                    <input asp-for="Score" max="10" min="0" class="form-control" /> / 10
                    <span asp-validation-for="Score" class="text-danger" />
                </div>
            </div>

            <div class="section">
                <a data-toggle="collapse" href=".advanced">Advanced Options</a>
            </div>


            <div class="collapse advanced container">

                <div class="form-group">
                    <label asp-for="Storage_Type" class="col-md-2 control-label"></label>
                    <div class="col-md-10 form-field">
                        <select asp-for="Status" class="form-control">
                            <option value="">Select storage type</option>
                            <option value="1">Hard Drive</option>
                            <option value="6">External HD</option>
                            <option value="7">NAS</option>
                            <option value="8">Blu-ray</option>
                            <option value="2">DVD / CD</option>
                            <option value="4">Retail DVD</option>
                            <option value="5">VHS</option>
                            <option value="3">None</option>
                        </select>
                        <span asp-validation-for="Storage_Type" class="text-danger" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Storage_Value" class="col-md-2 control-label"></label>
                    <div class="col-md-10 form-field">
                        <input asp-for="Storage_Value" class="form-control" />
                        <span asp-validation-for="Storage_Value" class="text-danger" />
                        Value may be number of discs, tapes, or size in gigabytes for hard-drive storage types
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Times_Rewatched" class="col-md-2 control-label"></label>
                    <div class="col-md-10 form-field">
                        <input asp-for="Times_Rewatched" class="form-control" />
                        <span asp-validation-for="Times_Rewatched" class="text-danger" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Rewatch_Value" class="col-md-2 control-label"></label>
                    <div class="col-md-10 form-field">
                        <input asp-for="Rewatch_Value" class="form-control" />
                        <span asp-validation-for="Rewatch_Value" class="text-danger" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Date_Start" class="col-md-2 control-label"></label>
                    <div class="col-md-10 form-field">
                        <input asp-for="Date_Start" type="date" value="null" class="form-control" />
                        <span asp-validation-for="Date_Start" class="text-danger" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Date_Finish" class="col-md-2 control-label"></label>
                    <div class="col-md-10 form-field">
                        <input asp-for="Date_Finish" type="date" value="null" class="form-control" />
                        <span asp-validation-for="Date_Finish" class="text-danger" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Priority" class="col-md-2 control-label"></label>
                    <div class="col-md-10 form-field">
                        <input asp-for="Priority" class="form-control" />
                        <span asp-validation-for="Priority" class="text-danger" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Enable_Discussion" class="col-md-2 control-label"></label>
                    <div class="col-md-10">
                        <input type="checkbox" name="Enable_Discussion" value="1" class="form-check" />

                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Enable_Rewatching" class="col-md-2 control-label"></label>
                    <div class="col-md-10">
                        <input type="checkbox" name="Enable_Rewatching" value="1" class="form-check" />

                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Comments" class="col-md-2 control-label"></label>
                    <div class="col-md-10">
                        <textarea asp-for="Comments" rows="5" cols="40" class="form-control"></textarea>
                        <span asp-validation-for="Comments" class="text-danger" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Tags" class="col-md-2 control-label"></label>
                    <div class="col-md-10">
                        <textarea asp-for="Tags" rows="5" cols="40" class="form-control" ></textarea>
                        <span asp-validation-for="Tags" class="text-danger" />
                        Use commas to separate tags.
                    </div>
                </div>

            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>

        </div>
    </div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}